models:
  dispersion_filenames:
    blue: '/Users/andycasey/thesis/old.scope/standards/UVES580/GES_UVESRed580_Lambda.fits'
    red: '/Users/andycasey/thesis/old.scope/standards/HR21/GES_HR21_Lambda.fits'
  flux_filenames:
    blue:
      folder: '/Users/andycasey/thesis/old.scope/standards/UVES580/GES_4600_alfa+0.4_fits/'
      re_match: '[s|p](?P<teff>[0-9]+):g\+(?P<logg>[0-9.]+).+z(?P<feh>[0-9.+-]+).+fits$'
    red: 
      folder: '/Users/andycasey/thesis/old.scope/standards/HR21/GES_HR21_alfa+0.4_fits/'
      re_match: '[s|p](?P<teff>[0-9]+):g\+(?P<logg>[0-9.]+).+z(?P<feh>[0-9.+-]+).+fits$'
interpolation: linear
parallelism: 32
verbosity: debug
normalise_observed:
  blue:
    perform: yes
    order: 3
    knot_spacing: 20
    lower_sigma_clip: free
    upper_sigma_clip: free
  red:
    perform: true
    order: 3
    knot_spacing: 20
    lower_sigma_clip: free
    upper_sigma_clip: free
doppler_correct:
  perform_initial_measurement: no
  initial_template: standards/template.fits
  blue:
    allow_shift: true
  red:
    allow_shift: true
smooth_model_flux:
  blue:
    perform: yes
    mode: gaussian
    kernel: free
  red:
    perform: yes
    mode: gaussian
    kernel: free
priors:
  normalise_observed.blue.lower_sigma_clip: 1.2
  normalise_observed.blue.upper_sigma_clip: 5.0
  normalise_observed.red.lower_sigma_clip: 1.2
  normalise_observed.red.upper_sigma_clip: 5.0
  teff: 4500
  logg: 2.0
  feh: -1.0
  smooth_model_flux.blue.kernel: 0.10
  smooth_model_flux.red.kernel: 0.10
  doppler_correct.blue.allow_shift: 0
  doppler_correct.red.allow_shift: 0
